# Generated by Django 6.0.3 on 2026-04-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accessories', 'Accessories'), ('gadgets', 'Accessories Gadgets'), ('lifestyle', 'Life Style'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('other', 'Other')], max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.PositiveIntegerField(default=20)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('image', models.ImageField(upload_to='deals/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deal Product',
                'verbose_name_plural': 'Deal Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
