# Generated by Django 6.0.3 on 2026-04-10 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', "Men's Fashion"), ('women', "Women's Fashion"), ('electronics', 'Electronics'), ('mobile', 'Mobile & Accessories'), ('home', 'Home & Kitchen'), ('beauty', 'Beauty & Grooming'), ('grocery', 'Groceries'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
